# validation_config.yaml
path: F:\dev\school\dissertation\dataset\zebra_v1 # <--- Root folder of your real data
train: train/images
val: val/images
test: test/images

nc: 1 # change if you have more classes
names: ["zebra"]
